### ISSUE TITLE
what is cur_sclk?

### ISSUE THREAD

**Issue by hsadasiv** [AMDResearch/omniperf#149]
Hello,

seems on gfx90a, cur_sclk on the web omniperf report is 800MHz whereas I can see sclk going to 1700MHz using rocm-smi (only when the program runs). 
PS: I did force the clk using "rocm-smi -d 0 --setperfdeterminism 1700" and made sure to run the process on gpuid: 0

**Comment by feizheng10** [comment]
Thanks for reporting it.
However, it might be a complicated question to answer: It all depends on the vbios version and rocm-smi version...
I believe omniperf only retrieves cur_sclk from rocm-smi. On gfx90a, with latest vbios, you might not be able to set/fix the sclk.
You might try: ricn-smi --setperflevel high

**Comment by hsadasiv** [comment]
Does cur_sclk mean current system clock?
if so, should Omniperf measure the clock when it goes high to 1700MHz? I can see rocm-smi catching it as soon as it goes up.

**Comment by arghdos** [comment]
I kinda agree with this.  I think _ideally_ for a lot of the PoP metrics, we should be actively sampling the clock during execution of the kernels.  (I mean, _really_ ideally, the profiler would spit this sorta info out for us).  But, we could fairly easily spin up a background process that samples clock rates over the lifetime of an app and reports back an average once all runs are completed?

Right now it looks like we run it on a cold GPU when gathering the specs?

https://github.com/AMDResearch/omniperf/blob/ed31b8a988b0fde6a5e11bc949417c82c6db1abc/src/utils/specs.py#L239

which is bound to give interesting answers if e.g., an app kicks the clock up significantly then spams FLOPS.

**Comment by arghdos** [comment]
Aha, I'm wrong, we take `$sclk` from here:

https://github.com/AMDResearch/omniperf/blob/ed31b8a988b0fde6a5e11bc949417c82c6db1abc/src/omniperf_analyze/utils/parser.py#L492

i.e., _not_ `cur_sclk`, which ends up being pulled from the max sclk here:

https://github.com/AMDResearch/omniperf/blob/ed31b8a988b0fde6a5e11bc949417c82c6db1abc/src/utils/specs.py#L113

from rocminfo.

This is ... better at least, because it's some _theoretical_ maximum value of FLOPs and the like you could achieve, it just doesn't take the achieved clock for your kernel into account (I think we might actually be able to do this via GRBM_GUI_ACTIVE... maybe)

**Comment by coleramos425** [comment]
This is related to issue #245. Closing ticket and linking PR #246 which closes the issue.
