### ISSUE TITLE
Issues with Omniperf installation

### ISSUE THREAD

**Issue by CongMa13** [AMDResearch/omniperf#427]
**Describe the bug**
The omniperf cannot be installed from source code. 

Got an error message when following the installation instructions https://rocm.docs.amd.com/projects/omniperf/en/latest/install/core-install.html

```
root@xxx:/home/xxx/work/forks/omniperf/omniperf-rocm-6.2.1/build# make install                                                                                                    Install the project...                                                                                                                                                                           -- Install configuration: "Release"                                                                                                                                                              -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/omniperf                                                                                                                     -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/requirements.txt                                                                                                             -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/argparser.py                                                                                                                 -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/config.py                                                                                                                    -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/omniperf_base.py                                                                                                             -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/roofline.py                                                                                                                  -- Up-to-date: /home/xxx/local/omniperf/2.0.1/libexec/omniperf/VERSION                                                                                                                      CMake Error at cmake_install.cmake:54 (file):                                                                                                                                                      file INSTALL cannot find                                                                                                                                                                         "/home/xxx/work/forks/omniperf/omniperf-rocm-6.2.1/VERSION.sha": No                                                                                                                         such file or directory.  
```

**Development Environment:**
 - Linux Distribution:  Ubuntu20.04
 - Omniperf Version: 6.2
 - GPU:  Mi250

**To Reproduce**
1. Download the source code package
2. Build (https://rocm.docs.amd.com/projects/omniperf/en/latest/install/core-install.html#install-from-source)
2. `make install` 

**Additional context**
Checked the CMakeLists.txt file, the VERSION.sha is only generated when it is a git clone. 

Installation finished when I cloned the git repo instead of using the source code package.

**Comment by etiennemlb** [comment]
Getting the same error.
In case we download the tar.gz and not do a git clone, what should the VERSION.sha contain ? Currently, IO workaround the issue like so:
```
# if(${GIT_CLONE})
    configure_file(${PROJECT_SOURCE_DIR}/cmake/VERSION.sha.in
                   ${PROJECT_SOURCE_DIR}/VERSION.sha @ONLY)
# endif()
```

**Comment by coleramos425** [comment]
Assigning to project PM for triage.

**Comment by coleramos425** [comment]
Thanks for reporting. @etiennemlb / @CongMa13 my first guess is that this occurred because you installed the incorrect tarball. We have a specific release tarball that's specially packaged, e.g.
![image](https://github.com/user-attachments/assets/c068ace7-0763-40b2-873d-23af475dc46f)

Can you please try again with this and let us know if your issue persists?
https://github.com/ROCm/omniperf/releases/download/v2.1.0/omniperf-v2.1.0.tar.gz

**Comment by etiennemlb** [comment]
It successfully installed, I guess this issue can be closed. That said, I still believe there is a bug in that you should be able to build the soft even if VERSION.sha is not present.

**Comment by ppanchad-amd** [comment]
Hi @etiennemlb. Glad you are able to successfully install.  We will leave this ticket open for the time being to investigate if there is a bug in being able to build even if VERSION.sha is not present. Thanks!

**Comment by schung-amd** [comment]
Hi, this file is used whenever we query for the version, which is going to occur every time `omniperf analyze` is used. When building from a git clone, we use `configure_file` to generate `VERSION.sha` from information in `.git`. If you do this for the tarball by commenting out the check you'll create an empty `VERSION.sha`, which allows the build to progress but does not provide any information. 

Because of this, I don't think it makes sense to allow building from the tarball without this file present, which would simply suppress the issue and not address it. The user would have to provide the proper `VERSION.sha` for their release for proper functionality. As noted above the official release tarballs should contain this file to begin with, so I don't see a problem here.

**Comment by schung-amd** [comment]
Closing this as the main issue has been addressed. Feel free to comment if you have further questions or would like additional guidance and we can reopen it.
