### ISSUE TITLE
Rocprof: Profiling data is corrupt

### ISSUE THREAD

**Issue by clphuong** [AMDResearch/omniperf#44]
Description: Attempting to profile RESNET50 workload results in "**profiling data is corrupt**" message

System details
git checkout python-logging
OS/distro: Ubuntu 5.15.0-52-generic #58~20.04.1-Ubuntu
ROCm Version: 5.2.3
Omniperf Version: 1.0.4dev
Logs of crash output:

Steps to reproduce:

Within docker container of resnet50 (https://confluence.amd.com/display/MLSE/MLPerf-1.1-ResNet50v1.5):
copy command into run.sh: 
`#!/bin/bash 
python3 -u -m mlperf_utils.bind_launch --nproc_per_node 1 --auto_binding ./main.py --amp --dynamic-loss-scale --lr-schedule polynomial --num-gpus 4 --mom 0.9 --wd 0.0002 --lr 9.1 --prof 100 --warmup 2 --epochs 1 --nhwc --use-lars -b 256 --eval-offset 1 --get-logs --submission-platform MI200system --num-nodes 1   --no-checkpoints --raport-file raport.json -j32 -p 100 --arch resnet50 --data /data/imagenet_pytorch 2>&1 | tee -a  run.log.txt`

Execute profiling command:
`omniperf profile --name resnet50 --path  /data/imagenet_pytorch/RN50FP16_DATA2 -- run.sh`

At the end of data collection execution, observe Profile data is corrupt message.

**Comment by coleramos425** [comment]
Looks like you may be reaching limitations within rocProfiler.

@clphuong we'd ask that you first try profiling there to rule out the possibility this is a rocProfiler issue:

1. [Install rocProfiler](https://rocmdocs.amd.com/en/latest/ROCm_Tools/ROCm-Tools.html) 
2. Set rocProf path
3. `$ROCPROF_CMD -i input.txt ./run.sh`

If your findings suggest otherwise, we're happy to look into this issue further.

**Comment by coleramos425** [comment]
Closing inactive ticket. Reopen if necessary.
