### ISSUE TITLE
Filtering using multiple kernel substrings 

### ISSUE THREAD

**Issue by ashesh2512** [AMDResearch/omniperf#443]
Hello, is it possible to filter kernels using multiple kernel substrings? For instance, I am interested in profiling two kernels, one is named ABC, other XYZ. How may I do so in the same omniperf run? What is the appropriate syntax?

**Comment by ppanchad-amd** [comment]
Hi @ashesh2512. Internal ticket has been created to assist with your question. Thanks!

**Comment by coleramos425** [comment]
Yes, Omniperf does support filtering multiple kernels via substrings. The appropriate syntax for such behavior would follow:
```console
$ omniperf profile -n my_app -k ABC XYZ -- ./you/app/binary
```
where each kernel substring is space-separated.

**Comment by ashesh2512** [comment]
Thank you! In such a scenario, how would one pass in the dispatch IDs? Would that be space-separated too, with the first value corresponding to the first substring, and so on?

**Comment by darren-amd** [comment]
Hi @ashesh2512,

Passing dispatch IDs would be in a similar fashion, such as:

`
$ omniperf profile -n my_app -d 0 1 -- ./you/app/binary
`

You can find further documentation here: [Filtering Options](https://rocm.docs.amd.com/projects/omniperf/en/latest/how-to/profile/mode.html#filtering-options)

**Comment by ashesh2512** [comment]
The documentation doesn’t have an example with multiple substrings. So if I specify -k ABC XYZ -d 0 7, the expected behavior is to record the 0 dispatch for ABC and 7 dispatch for XYZ?

**Comment by darren-amd** [comment]
Hi @ashesh2512,

From my understanding as well as discussions with the internal team, dispatch ID's are independent from kernel substrings, and so the recommended use case would be to specify one of them rather than both. I tried a few calls and found that the behavior with multiple filters was a bit inconsistent. 

You can also check out the warning here: [Omniperf Filtering](https://rocm.docs.amd.com/projects/omniperf/en/latest/how-to/profile/mode.html#filtering-options)
